image_finetune: True

output_dir: "outputs"
pretrained_model_path: "pretrained_models/StableDiffusion/stable-diffusion-inpainting"

zero_snr:                True
train_cfg:               True
snr_gamma:               5.0

validation_kwargs:
  guidance_scale:        3.0


train_data:
  dataset_class: PartChipDatasetPasteInpaint
  args:
    split: "train"
    root: "{PATH_TO_DATA}"
    data_info_json:  "{YOUR_JSON}"
    sample_size: [512, 512] 
    mask_thr: 0.2


validation_data:
  dataset_class: PartChipDatasetPasteInpaint
  args:
    split: "val"
    root: "/mnt/workspace/workgroup/wangbenzhi.wbz/RealisHuman/"
    data_info_json:  "data/face_example/face_stage2_val.json"
    sample_size: [512, 512] #wbz [ 960, 544 ] 
    mask_thr: 0.2
    mask_gap: 30
trainable_modules:
  - "."

unet_checkpoint_path: ""

lr_scheduler:     "constant_with_warmup"
learning_rate:    5e-5
lr_warmup_steps:  5000
train_batch_size: 16 
validation_batch_size: 16 

max_train_epoch:      -1
max_train_steps:      100000
checkpointing_epochs: -1
checkpointing_steps:  10000
checkpointing_steps_tuple:  [ ]


global_seed: 42
mixed_precision_training: True
enable_xformers_memory_efficient_attention: True

is_debug: False
